class_name Types
extends RefCounted


enum BARLINES { SINGLE, DOUBLE, END, ENDREP, STARTREP }

enum DYNAMICS { PIANISSIMO, PIANO, MEZZOPIANO, MEZZOFORTE, FORTE, FORTISSIMO, CRESCENDO, DIMINUENDO }

enum ORFFS { RHYTHM_STICKS, MARACAS, WOODBLOCK, BELL_STRAPS, TUBULAR_WOODBLOCK, TRIANGLE, CYMBALS, TAMBOURINE, HAND_DRUM, RECO_RECO, CASTANETS}

enum SECTIONS { A, B, C, D, E, F, G, H }
